# SPDX-FileCopyrightText: 2026 LibreSign
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "xobject-template"
SPDX-PackageSupplier = "LibreSign"
SPDX-PackageDownloadLocation = "https://github.com/LibreSign/xobject-template"

[[annotations]]
path = ["src/**", "tests/**", "benchmarks/**", "scripts/**", ".github/**", "*.php", "*.xml", "*.json", "*.json5", "*.cjs", "docker-compose.yml"]
precedence = "override"
SPDX-FileCopyrightText = "2026 LibreSign"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["phpunit.xml.dist", "vendor-bin/**/composer.json"]
precedence = "override"
SPDX-FileCopyrightText = "2026 LibreSign"
SPDX-License-Identifier = "AGPL-3.0-or-later"
