name: dco

on:
  pull_request:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tim-actions/dco@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
