# SPDX-FileCopyrightText: 2026 LibreSign
# SPDX-License-Identifier: AGPL-3.0-or-later

name: dependabot-auto-triage

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-auto-triage:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v3
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            dependencies
            security
