# SPDX-FileCopyrightText: 2026 LibreSign
# SPDX-License-Identifier: AGPL-3.0-or-later

name: docker

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint hadolint --failure-threshold error - < .docker/Dockerfile
      - name: Validate compose
        run: docker compose config > /dev/null
