name: psalm

on:
  pull_request:
  push:
    branches: [main]

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: composer install --no-interaction --prefer-dist
      - run: composer bin psalm install --no-interaction --prefer-dist
      - run: composer psalm
